# Generated by Django 4.0 on 2023-09-04 17:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_blogmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, max_length=1000, null=True, populate_from='title', unique=True),
        ),
    ]
