# Generated by Django 4.0 on 2023-09-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_bloggers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggers',
            name='blogs',
        ),
        migrations.AddField(
            model_name='bloggers',
            name='blogs',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='bloggers',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
