# Generated by Django 4.0 on 2023-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_bloggers_blogs_bloggers_blogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggers',
            name='blogs',
        ),
        migrations.AddField(
            model_name='bloggers',
            name='blogs',
            field=models.ManyToManyField(related_name='bloggers', to='app1.BlogModel'),
        ),
    ]
