# Generated by Django 4.0 on 2023-09-11 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_addcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
