# Generated by Django 4.0 on 2023-09-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_blogmodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='count1',
            field=models.IntegerField(default=0),
        ),
    ]
