# Generated by Django 4.0 on 2023-09-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_blogmodel_count1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
