# Generated by Django 4.0 on 2023-09-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_blogmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
    ]
